enum CollectionTemplateType {
  blank,
  travelPlanner,
  propertyManagement,
  projectPlanning,
  eventPlanning,
  fitnessTracker,
  recipeBook,
  jobSearch,
  movingChecklist,
  petCare,
  vehicleMaintenance,
  budgetPlanner,
  studyPlanner,
  homeRenovation,
  weddingPlanner,
  freelanceTracker,
  diplomasCertificates,
  bankDocuments,
  healthRecords,
  taxDocuments,
  warrantyTracker,
  subscriptionManager,
  homeMaintenance,
  movieLibrary,
  readingList,
  wineCellar,
  medicalTracker,
  emergencyContacts,
  digitalAccounts,
  insurancePolicies,
}

extension CollectionTemplateTypeX on CollectionTemplateType {
  String get key {
    return switch (this) {
      CollectionTemplateType.blank => 'blank',
      CollectionTemplateType.travelPlanner => 'travel_planner',
      CollectionTemplateType.propertyManagement => 'property_management',
      CollectionTemplateType.projectPlanning => 'project_planning',
      CollectionTemplateType.eventPlanning => 'event_planning',
      CollectionTemplateType.fitnessTracker => 'fitness_tracker',
      CollectionTemplateType.recipeBook => 'recipe_book',
      CollectionTemplateType.jobSearch => 'job_search',
      CollectionTemplateType.movingChecklist => 'moving_checklist',
      CollectionTemplateType.petCare => 'pet_care',
      CollectionTemplateType.vehicleMaintenance => 'vehicle_maintenance',
      CollectionTemplateType.budgetPlanner => 'budget_planner',
      CollectionTemplateType.studyPlanner => 'study_planner',
      CollectionTemplateType.homeRenovation => 'home_renovation',
      CollectionTemplateType.weddingPlanner => 'wedding_planner',
      CollectionTemplateType.freelanceTracker => 'freelance_tracker',
      CollectionTemplateType.diplomasCertificates => 'diplomas_certificates',
      CollectionTemplateType.bankDocuments => 'bank_documents',
      CollectionTemplateType.healthRecords => 'health_records',
      CollectionTemplateType.taxDocuments => 'tax_documents',
      CollectionTemplateType.warrantyTracker => 'warranty_tracker',
      CollectionTemplateType.subscriptionManager => 'subscription_manager',
      CollectionTemplateType.homeMaintenance => 'home_maintenance',
      CollectionTemplateType.movieLibrary => 'movie_library',
      CollectionTemplateType.readingList => 'reading_list',
      CollectionTemplateType.wineCellar => 'wine_cellar',
      CollectionTemplateType.medicalTracker => 'medical_tracker',
      CollectionTemplateType.emergencyContacts => 'emergency_contacts',
      CollectionTemplateType.digitalAccounts => 'digital_accounts',
      CollectionTemplateType.insurancePolicies => 'insurance_policies',
    };
  }

  String get label {
    return switch (this) {
      CollectionTemplateType.blank => 'Blank Collection',
      CollectionTemplateType.travelPlanner => 'Travel Planner',
      CollectionTemplateType.propertyManagement => 'Property Management',
      CollectionTemplateType.projectPlanning => 'Project Planning',
      CollectionTemplateType.eventPlanning => 'Event Planning',
      CollectionTemplateType.fitnessTracker => 'Fitness Tracker',
      CollectionTemplateType.recipeBook => 'Recipe Book',
      CollectionTemplateType.jobSearch => 'Job Search',
      CollectionTemplateType.movingChecklist => 'Moving Checklist',
      CollectionTemplateType.petCare => 'Pet Care',
      CollectionTemplateType.vehicleMaintenance => 'Vehicle Maintenance',
      CollectionTemplateType.budgetPlanner => 'Budget Planner',
      CollectionTemplateType.studyPlanner => 'Study Planner',
      CollectionTemplateType.homeRenovation => 'Home Renovation',
      CollectionTemplateType.weddingPlanner => 'Wedding Planner',
      CollectionTemplateType.freelanceTracker => 'Freelance Tracker',
      CollectionTemplateType.diplomasCertificates => 'Diplomas & Certificates',
      CollectionTemplateType.bankDocuments => 'Bank Documents (RIB)',
      CollectionTemplateType.healthRecords => 'Health Records',
      CollectionTemplateType.taxDocuments => 'Tax Documents',
      CollectionTemplateType.warrantyTracker => 'Warranty Tracker',
      CollectionTemplateType.subscriptionManager => 'Subscription Manager',
      CollectionTemplateType.homeMaintenance => 'Home Maintenance',
      CollectionTemplateType.movieLibrary => 'Movie Library',
      CollectionTemplateType.readingList => 'Reading List',
      CollectionTemplateType.wineCellar => 'Wine Cellar',
      CollectionTemplateType.medicalTracker => 'Medical Tracker',
      CollectionTemplateType.emergencyContacts => 'Emergency Contacts',
      CollectionTemplateType.digitalAccounts => 'Digital Accounts',
      CollectionTemplateType.insurancePolicies => 'Insurance Policies',
    };
  }

  static CollectionTemplateType fromKey(String raw) {
    return switch (raw.trim().toLowerCase()) {
      'blank' => CollectionTemplateType.blank,
      'travel_planner' => CollectionTemplateType.travelPlanner,
      'property_management' => CollectionTemplateType.propertyManagement,
      'project_planning' => CollectionTemplateType.projectPlanning,
      'event_planning' => CollectionTemplateType.eventPlanning,
      'fitness_tracker' => CollectionTemplateType.fitnessTracker,
      'recipe_book' => CollectionTemplateType.recipeBook,
      'job_search' => CollectionTemplateType.jobSearch,
      'moving_checklist' => CollectionTemplateType.movingChecklist,
      'pet_care' => CollectionTemplateType.petCare,
      'vehicle_maintenance' => CollectionTemplateType.vehicleMaintenance,
      'budget_planner' => CollectionTemplateType.budgetPlanner,
      'study_planner' => CollectionTemplateType.studyPlanner,
      'home_renovation' => CollectionTemplateType.homeRenovation,
      'wedding_planner' => CollectionTemplateType.weddingPlanner,
      'freelance_tracker' => CollectionTemplateType.freelanceTracker,
      'diplomas_certificates' => CollectionTemplateType.diplomasCertificates,
      'bank_documents' => CollectionTemplateType.bankDocuments,
      'health_records' => CollectionTemplateType.healthRecords,
      'tax_documents' => CollectionTemplateType.taxDocuments,
      'warranty_tracker' => CollectionTemplateType.warrantyTracker,
      'subscription_manager' => CollectionTemplateType.subscriptionManager,
      'home_maintenance' => CollectionTemplateType.homeMaintenance,
      'movie_library' => CollectionTemplateType.movieLibrary,
      'reading_list' => CollectionTemplateType.readingList,
      'wine_cellar' => CollectionTemplateType.wineCellar,
      'medical_tracker' => CollectionTemplateType.medicalTracker,
      'emergency_contacts' => CollectionTemplateType.emergencyContacts,
      'digital_accounts' => CollectionTemplateType.digitalAccounts,
      'insurance_policies' => CollectionTemplateType.insurancePolicies,
      _ => CollectionTemplateType.blank,
    };
  }
}
